BSI/manager-mvc/Models/Scheme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace manager_mvc.Models
{
    public class Scheme
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Boolean isCurrentScheme { get; set; }
        public List<Scheme_Sound> Sounds { get; set; }
    }
}

BSI/manager-mvc/Models/SchemeList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace manager_mvc.Models
{
    public class SchemeList
    {
        public List<Scheme> lstSchemes { get; set; }
    }
}

BSI/manager-mvc/Models/Scheme_Sound.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace manager_mvc.Models
{
    public class Scheme_Sound
    {
        //public string Id { get; set; }
        public string SchemeId { get; set; }
        public string SoundId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int SwitchNumber { get; set; }
        public int Volume { get; set; }
        public int Balance { get; set; }
        public int Fade { get; set; }
        public int MinInterval { get; set; }
        public int MaxInterval { get; set; }
    }
}

BSI/manager-mvc/Models/Sound.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace manager_mvc.Models
{
    public class Sound
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        int Volume { get; set; }
        int Balance { get; set; }
        int Fade { get; set; }
    }
}

BSI/manager-mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace manager_mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

BSI/manager-mvc/Controllers/SchemesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using manager_mvc.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace manager_mvc.Controllers
{
    public class SchemesController : Controller
    {
        private string Host = Environment.GetEnvironmentVariable("AirhornDB_URL");

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            // Get all local sound schemes and list them
            // Indicate the current scheme 
            SchemeList lstSchemes = new SchemeList();
            lstSchemes = await List();
            return View(lstSchemes);
        }

        //public async Task Load(Guid id)
        //{
        //    var httpClient = new HttpClient();
        //    httpClient.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("MyClient", "1.0"));
        //    // Get the json string
        //    var result = await httpClient.GetStringAsync(String.Format("{0}/schemes/{1}", Host, id));
        //    // Parse it into a Scheme Object
        //    SoundScheme s = (SoundScheme)JsonConvert.DeserializeObject(result);
        //    this.isCurrentScheme = s.isCurrentScheme;
        //    this.SchemeId = s.SchemeId;
        //    this.Name = s.Name;
        //}

        public async Task<SchemeList> List()
        {
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("MyClient", "1.0"));
                // Get the json string
                var result = await httpClient.GetStringAsync(String.Format("{0}/schemes", Host));
                // Parse it into a List of Scheme Objects
                List<Scheme> s = JsonConvert.DeserializeObject<List<Scheme>>(result);
                SchemeList lstSchemes = new SchemeList();
                lstSchemes.lstSchemes = s;
                // Load each scheme's sound metadata
                foreach (Scheme scheme in s)
                {
                    string url = String.Format("{0}/scheme-sounds?SchemeId={1}", Host, scheme.Id);
                    var ss = await httpClient.GetStringAsync(url);
                    List<Scheme_Sound> lstSS = JsonConvert.DeserializeObject<List<Scheme_Sound>>(ss);
                    scheme.Sounds = lstSS;
                }
                return lstSchemes;
            }
        }
    }
}

BSI/manager-mvc/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

BSI/manager-mvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BSI/manager-mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

BSI/manager-mvc/Views/Schemes/Index.cshtml
@model manager_mvc.Models.SchemeList
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>Local Sound Schemes</h2>

@{
}
<h3>You have @Model.lstSchemes.Count sound schemes.</h3>


<!-- List of local sound schemes-->
<div class="row">
    <div class="col-md-3">Name</div>
    <div class="col-md-3">Current Scheme</div>
    <div class="col-md-6">Sounds</div>
</div>
@foreach (var item in Model.lstSchemes)
{
    <div class="row">
        <div class="col-md-3">@item.Name</div>
        <div class="col-md-3">@item.isCurrentScheme</div>
        <div class="col-md-6">
            @foreach (var sound in item.Sounds)
            {
                <div class="row">
                    <div class="col-md-2">@sound.Name</div>
                    <div class="col-md-2">
                        @if (sound.Type == "SWITCH")
                        {
                            @sound.Type @sound.SwitchNumber
                        }
                        else
                        {
                            @sound.Type
                        }
                    </div>
                </div>
            }
        </div>
    </div>
}

BSI/manager-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Airhorn Manager</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Airhorn Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-controller="Home" asp-action="Index">Home</a></li>*@
                    <li><a asp-controller="Schemes" asp-action="Index">Sound Schemes</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Brinston Sound Images</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>